version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app_network
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    env_file:
      - .env

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app_network
    env_file:
      - .env

networks:
  app_network:
    driver: bridge
