version: '3.9'

services:

  backend:
    build: .
    container_name: fastapi_backend
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
    networks:
      - app_network

  nginx:
    image: nginx:1.23-alpine
    container_name: nginx_frontend
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./Layout/dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
